// Generated by gencpp from file yeti_snowplow/obstacles.msg
// DO NOT EDIT!


#ifndef YETI_SNOWPLOW_MESSAGE_OBSTACLES_H
#define YETI_SNOWPLOW_MESSAGE_OBSTACLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <yeti_snowplow/obstacle.h>

namespace yeti_snowplow
{
template <class ContainerAllocator>
struct obstacles_
{
  typedef obstacles_<ContainerAllocator> Type;

  obstacles_()
    : obstacles()  {
    }
  obstacles_(const ContainerAllocator& _alloc)
    : obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::yeti_snowplow::obstacle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::yeti_snowplow::obstacle_<ContainerAllocator> >::other >  _obstacles_type;
  _obstacles_type obstacles;




  typedef boost::shared_ptr< ::yeti_snowplow::obstacles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yeti_snowplow::obstacles_<ContainerAllocator> const> ConstPtr;

}; // struct obstacles_

typedef ::yeti_snowplow::obstacles_<std::allocator<void> > obstacles;

typedef boost::shared_ptr< ::yeti_snowplow::obstacles > obstaclesPtr;
typedef boost::shared_ptr< ::yeti_snowplow::obstacles const> obstaclesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yeti_snowplow::obstacles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yeti_snowplow::obstacles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yeti_snowplow

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'yeti_snowplow': ['/home/ben/Catkin/catkin_ws_argon/src/rover_manual/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yeti_snowplow::obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yeti_snowplow::obstacles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yeti_snowplow::obstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yeti_snowplow::obstacles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yeti_snowplow::obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yeti_snowplow::obstacles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yeti_snowplow::obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1b14cf1472bdc7f2a4a7c32f2465997";
  }

  static const char* value(const ::yeti_snowplow::obstacles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1b14cf1472bdc7fULL;
  static const uint64_t static_value2 = 0x2a4a7c32f2465997ULL;
};

template<class ContainerAllocator>
struct DataType< ::yeti_snowplow::obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yeti_snowplow/obstacles";
  }

  static const char* value(const ::yeti_snowplow::obstacles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yeti_snowplow::obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "obstacle[] obstacles\n\
\n\
================================================================================\n\
MSG: yeti_snowplow/obstacle\n\
float32 x\n\
float32 y\n\
#x and y are relative to robot position and orientation\n\
float32 r\n\
#radius of obstacle\n\
bool dynamic\n\
#if object is or was previously moving, i.e. this is a new obstacle in this position\n\
";
  }

  static const char* value(const ::yeti_snowplow::obstacles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yeti_snowplow::obstacles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct obstacles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yeti_snowplow::obstacles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yeti_snowplow::obstacles_<ContainerAllocator>& v)
  {
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::yeti_snowplow::obstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YETI_SNOWPLOW_MESSAGE_OBSTACLES_H
