// Generated by gencpp from file yeti_snowplow/robot_position.msg
// DO NOT EDIT!


#ifndef YETI_SNOWPLOW_MESSAGE_ROBOT_POSITION_H
#define YETI_SNOWPLOW_MESSAGE_ROBOT_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yeti_snowplow
{
template <class ContainerAllocator>
struct robot_position_
{
  typedef robot_position_<ContainerAllocator> Type;

  robot_position_()
    : x(0.0)
    , y(0.0)
    , distance(0.0)
    , heading(0.0)  {
    }
  robot_position_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , distance(0.0)
    , heading(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _distance_type;
  _distance_type distance;

   typedef double _heading_type;
  _heading_type heading;




  typedef boost::shared_ptr< ::yeti_snowplow::robot_position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yeti_snowplow::robot_position_<ContainerAllocator> const> ConstPtr;

}; // struct robot_position_

typedef ::yeti_snowplow::robot_position_<std::allocator<void> > robot_position;

typedef boost::shared_ptr< ::yeti_snowplow::robot_position > robot_positionPtr;
typedef boost::shared_ptr< ::yeti_snowplow::robot_position const> robot_positionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yeti_snowplow::robot_position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yeti_snowplow::robot_position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yeti_snowplow

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'yeti_snowplow': ['/home/ben/Catkin/catkin_ws_argon/src/rover_manual/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yeti_snowplow::robot_position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yeti_snowplow::robot_position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yeti_snowplow::robot_position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yeti_snowplow::robot_position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yeti_snowplow::robot_position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yeti_snowplow::robot_position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yeti_snowplow::robot_position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30c3e373d4e8c564504331ea5d44f519";
  }

  static const char* value(const ::yeti_snowplow::robot_position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30c3e373d4e8c564ULL;
  static const uint64_t static_value2 = 0x504331ea5d44f519ULL;
};

template<class ContainerAllocator>
struct DataType< ::yeti_snowplow::robot_position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yeti_snowplow/robot_position";
  }

  static const char* value(const ::yeti_snowplow::robot_position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yeti_snowplow::robot_position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 distance\n\
float64 heading\n\
";
  }

  static const char* value(const ::yeti_snowplow::robot_position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yeti_snowplow::robot_position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.distance);
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yeti_snowplow::robot_position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yeti_snowplow::robot_position_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YETI_SNOWPLOW_MESSAGE_ROBOT_POSITION_H
