(cl:in-package rover_manual-msg)
(cl:export '(A-VAL
          A
          B-VAL
          B
          X-VAL
          X
          Y-VAL
          Y
          LB-VAL
          LB
          RB-VAL
          RB
          BACK-VAL
          BACK
          START-VAL
          START
          GUIDE-VAL
          GUIDE
          LS-VAL
          LS
          RS-VAL
          RS
          LEFTSTICK_LR-VAL
          LEFTSTICK_LR
          LEFTSTICK_UD-VAL
          LEFTSTICK_UD
          RIGHTSTICK_LR-VAL
          RIGHTSTICK_LR
          RIGHTSTICK_UD-VAL
          RIGHTSTICK_UD
          LT-VAL
          LT
          RT-VAL
          RT
          DPAD_LR-VAL
          DPAD_LR
          DPAD_UD-VAL
          DPAD_UD
))