// Generated by gencpp from file rover_manual/turn.msg
// DO NOT EDIT!


#ifndef ROVER_MANUAL_MESSAGE_TURN_H
#define ROVER_MANUAL_MESSAGE_TURN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_manual
{
template <class ContainerAllocator>
struct turn_
{
  typedef turn_<ContainerAllocator> Type;

  turn_()
    : angle(0.0)
    , stop(false)  {
    }
  turn_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , stop(false)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;

   typedef uint8_t _stop_type;
  _stop_type stop;




  typedef boost::shared_ptr< ::rover_manual::turn_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_manual::turn_<ContainerAllocator> const> ConstPtr;

}; // struct turn_

typedef ::rover_manual::turn_<std::allocator<void> > turn;

typedef boost::shared_ptr< ::rover_manual::turn > turnPtr;
typedef boost::shared_ptr< ::rover_manual::turn const> turnConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_manual::turn_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_manual::turn_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_manual

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rover_manual': ['/home/ben/Catkin/catkin_ws_argon/src/rover_manual/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_manual::turn_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_manual::turn_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_manual::turn_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_manual::turn_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_manual::turn_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_manual::turn_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_manual::turn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d13a914ba0846a78d8f6016249a48c2";
  }

  static const char* value(const ::rover_manual::turn_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d13a914ba0846a7ULL;
  static const uint64_t static_value2 = 0x8d8f6016249a48c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_manual::turn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_manual/turn";
  }

  static const char* value(const ::rover_manual::turn_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_manual::turn_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle\n\
bool stop\n\
";
  }

  static const char* value(const ::rover_manual::turn_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_manual::turn_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct turn_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_manual::turn_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_manual::turn_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MANUAL_MESSAGE_TURN_H
