// Generated by gencpp from file rover_manual/vesc_state_stamped.msg
// DO NOT EDIT!


#ifndef ROVER_MANUAL_MESSAGE_VESC_STATE_STAMPED_H
#define ROVER_MANUAL_MESSAGE_VESC_STATE_STAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <rover_manual/vesc_state.h>

namespace rover_manual
{
template <class ContainerAllocator>
struct vesc_state_stamped_
{
  typedef vesc_state_stamped_<ContainerAllocator> Type;

  vesc_state_stamped_()
    : header()
    , state()  {
    }
  vesc_state_stamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::rover_manual::vesc_state_<ContainerAllocator>  _state_type;
  _state_type state;




  typedef boost::shared_ptr< ::rover_manual::vesc_state_stamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_manual::vesc_state_stamped_<ContainerAllocator> const> ConstPtr;

}; // struct vesc_state_stamped_

typedef ::rover_manual::vesc_state_stamped_<std::allocator<void> > vesc_state_stamped;

typedef boost::shared_ptr< ::rover_manual::vesc_state_stamped > vesc_state_stampedPtr;
typedef boost::shared_ptr< ::rover_manual::vesc_state_stamped const> vesc_state_stampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_manual::vesc_state_stamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_manual::vesc_state_stamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_manual

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'rover_manual': ['/home/ben/catkin/catkin_ws_argon/src/rover_manual/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_manual::vesc_state_stamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_manual::vesc_state_stamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_manual::vesc_state_stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_manual::vesc_state_stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_manual::vesc_state_stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_manual::vesc_state_stamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_manual::vesc_state_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a2b3a0e5b5f10ce6bbf973d767cdc4d";
  }

  static const char* value(const ::rover_manual::vesc_state_stamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a2b3a0e5b5f10ceULL;
  static const uint64_t static_value2 = 0x6bbf973d767cdc4dULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_manual::vesc_state_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_manual/vesc_state_stamped";
  }

  static const char* value(const ::rover_manual::vesc_state_stamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_manual::vesc_state_stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Timestamped VESC open source motor controller state (telemetry)\n\
\n\
Header  header\n\
vesc_state state\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: rover_manual/vesc_state\n\
# Vedder VESC open source motor controller state (telemetry)\n\
\n\
# fault codes\n\
int32 FAULT_CODE_NONE=0\n\
int32 FAULT_CODE_OVER_VOLTAGE=1\n\
int32 FAULT_CODE_UNDER_VOLTAGE=2\n\
int32 FAULT_CODE_DRV8302=3\n\
int32 FAULT_CODE_ABS_OVER_CURRENT=4\n\
int32 FAULT_CODE_OVER_TEMP_FET=5\n\
int32 FAULT_CODE_OVER_TEMP_MOTOR=6\n\
\n\
float64 voltage_input        # input voltage (volt)\n\
float64 temperature_pcb      # temperature of printed circuit board (degrees Celsius)\n\
float64 current_motor        # motor current (ampere)\n\
float64 current_input        # input current (ampere)\n\
float64 speed                # motor electrical speed (revolutions per minute) \n\
float64 duty_cycle           # duty cycle (0 to 1)\n\
float64 charge_drawn         # electric charge drawn from input (ampere-hour)\n\
float64 charge_regen         # electric charge regenerated to input (ampere-hour)\n\
float64 energy_drawn         # energy drawn from input (watt-hour)\n\
float64 energy_regen         # energy regenerated to input (watt-hour)\n\
float64 displacement         # net tachometer (counts)\n\
float64 distance_traveled    # total tachnometer (counts)\n\
int32   fault_code\n\
";
  }

  static const char* value(const ::rover_manual::vesc_state_stamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_manual::vesc_state_stamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vesc_state_stamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_manual::vesc_state_stamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_manual::vesc_state_stamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "state: ";
    s << std::endl;
    Printer< ::rover_manual::vesc_state_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MANUAL_MESSAGE_VESC_STATE_STAMPED_H
